apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
    volumeMounts:
      - name: redis-storage
        mountPath: /data/redis
  volumes:
  - name: redis-storage
    emptyDir: {}