apiVersion: v1
kind: Pod
metadata:
  name: mypod-voulmesecret
spec:
  containers:
  - name: mypod-voulmesecret
    image: redis
    volumeMounts:
      - name:  foo
        mountPath: "/etc/foo"
        readOnly: true
  volumes:
    - name:  foo
      secret:
        secretName: mysecret-manifest